services:
  # competitivecoding:
  #   image: competitivecoding
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile
  

  mongodb-atlas:
    image: mongo
    container_name: mongodb-atlas
    environment:
      - MONGO_INITDB_ROOT_USERNAME=vivek
      - MONGO_INITDB_ROOT_PASSWORD=12345678
      - MONGO_INITDB_DATABASE=jai_shri_ram

    volumes:
      - ./data:/data/db  
    ports:
      - "27018:27017"
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb-atlas
      - ME_CONFIG_MONGODB_ADMINUSERNAME=vivek
      - ME_CONFIG_MONGODB_ADMINPASSWORD=12345678
      - ME_CONFIG_MONGODB_URL=mongodb://vivek:12345678@mongodb-atlas:27017/jai_shri_ram?authSource=admin

 
 